// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.10;

/**
 * @title PureFiData
 * @notice Represents the core data structure used for PureFi payload verification.
 * @dev This struct is typically encoded and signed by the PureFi Issuer off-chain.
 */
struct PureFiData {
    /// @notice The timestamp (in seconds) when the payload was generated. Used to check for expiration.
    uint64 timestamp;
    /// @notice The cryptographic ECDSA signature generated by an authorized PureFi Issuer.
    bytes signature;
    /// @notice The encoded package data containing specific verification rules, session ID, and routing info.
    bytes package;
}

/**
 * @title IPureFiVerifier
 * @notice Interface for the PureFi Verifier contract.
 * @dev Defines the standard functions, events, and custom errors for payload verification,
 * fee collection, and storage management (garbage collection).
 */
interface IPureFiVerifier {
    // =============================================================
    // EVENTS
    // =============================================================

    /**
     * @notice Emitted when a payload is successfully validated and its session is recorded.
     * @param caller The address that submitted the transaction (usually the user).
     * @param session The unique session ID of the processed payload to prevent replay attacks.
     */
    event PureFiPackageProcessed(address indexed caller, uint256 session);

    /**
     * @notice Emitted when expired sessions are successfully cleared from the contract's storage.
     * @param caller The address that triggered the storage cleanup.
     * @param sessionId The amount of sessions cleared (or the specific session ID, depending on implementation).
     */
    event PureFiStorageClear(address caller, uint256 sessionId);

    /**
     * @notice Emitted when accumulated fees are withdrawn from the contract.
     * @param feeCollector The authorized address receiving the withdrawn funds.
     * @param amount The amount of native tokens (or ERC20 tokens) withdrawn.
     */
    event Withdrawn(address feeCollector, uint256 amount);

    // =============================================================
    // CUSTOM ERRORS
    // =============================================================

    /// @notice Thrown when the payload's timestamp is older than the allowed grace period.
    error PureFiDataExpiredError();

    /// @notice Thrown when the provided payload byte array is smaller than the minimum required length.
    error TooShortPayloadError();

    /// @notice Thrown when a payload's session ID has already been marked as processed (Replay Attack protection).
    error AlreadyUsedPayloadError();

    /// @notice Thrown when the `msg.sender` does not match the mandatory `to` or `from` addresses specified in the package.
    error InvalidContractCallerError();

    /// @notice Thrown when a payload requiring a fee payment is submitted to the free `validatePayload` function.
    error PaidPayloadNotAllowed();

    /// @notice Thrown when the user provides insufficient `msg.value` or ERC20 allowance to cover the verification fee.
    error VerificationPaymentFailed();

    /// @notice Thrown when the internal native token transfer (`.call{value: ...}`) fails during a withdrawal.
    error WithdrawFailed();

    /// @notice Thrown when native currency (`msg.value`) is accidentally sent alongside an ERC20-paid payload.
    error ERC20PaymentError();

    // =============================================================
    // FUNCTIONS
    // =============================================================

    /**
     * @notice Validates a free PureFi payload and marks its session as processed.
     * @dev Extracts the signature, verifies the issuer, checks expiration, and prevents replays.
     * Reverts with `PaidPayloadNotAllowed` if the package contains a payment requirement.
     * @param payload The raw encoded bytes containing the timestamp, signature, and package.
     */
    function validatePayload(bytes calldata payload) external;

    /**
     * @notice Withdraws accumulated native currency to a specified account.
     * @dev Typically restricted to addresses with a specific fee collector role.
     * @param account The destination address where the withdrawn funds will be sent.
     * @param amount The exact amount of native tokens (wei) to withdraw.
     */
    function withdraw(address account, uint256 amount) external;

    /**
     * @notice Validates a PureFi payload that requires a fee payment (Native or ERC20).
     * @dev Parses the payment data from the package. If the token address is `address(0)`,
     * it expects native currency (`msg.value`). Otherwise, it attempts to pull ERC20 tokens via `transferFrom`.
     * @param _payload The raw encoded bytes containing the timestamp, signature, and package.
     */
    function paidValidatePayload(bytes calldata _payload) external payable;

    /**
     * @notice Clears expired sessions from storage to free up state and potentially refund gas.
     * @dev Iterates through the provided array and deletes the session timestamp if it is older than the retention period.
     * @param _sessions An array of session IDs to be checked and cleared.
     */
    function clearStorage(uint256[] memory _sessions) external;
}
